### ISSUE TITLE
Headers support

### ISSUE THREAD

**Issue by hvalls** [hvalls/reqi#1]
Add headers support:

```
name: slack/send
description: Send slack message 
url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXXXX/XXXXXXXXXXXXXX
method: post
body: "{ \"text\": \"This is a test message\" }"
headers:
  - name: Authorization
    value: Bearer XXXXXXXXXXXXX
```
