### ISSUE TITLE
Need to be able to parameterize template values 

### ISSUE THREAD

**Issue by hvalls** [hvalls/reqi#4]
```
name: slack/send
description: Send slack message 
url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXXXX/XXXXXXXXXXXXXX
method: post
body: "{ \"text\": \"{{ message }}\" }"
headers:
  - name: Authorization
    value: Basic aGVsbG8=
```

`$ reqi do slack/send -p "message=Hello!"`
